name: Deploy HTML to Somee

on:
  push:
    branches:
      - main   # chạy khi push nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Upload HTML qua FTP
      - name: Upload HTML via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: phat123.somee.com
          username: UncleFour
          password: Chukhjtinhnghich72*
          protocol: ftps
          local-dir: ./   # thư mục HTML của bạn
          server-dir: /test/
