name: ğŸš€ Deploy to inet via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Checkout source
        uses: actions/checkout@v4

      - name: ğŸ“¦ Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: phat123.somee.com
          username: UncleFour
          password: Chukhjtinhnghich72*
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /www.phat123.somee.com/1/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/README.md
